"""
Diffs every setting that differs between run_exp1.py and privacy_utility_curves.py
via static AST parsing (no execution, no data/GPU needed).
Output: revision_docs/script_divergence_report.md

TEMP: delete this script (and the report) once run_prism_privacy_sweep.py has
replaced both scripts above and they are retired.

Usage: python revision_scripts/diff_exp1_vs_privacy_curves.py
"""

from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).parent.parent
SCRIPT_A = ROOT / "experiments" / "run_exp1.py"
SCRIPT_B = ROOT / "experiments" / "privacy_utility_curves.py"
OUT = ROOT / "revision_docs" / "script_divergence_report.md"

# Module-level names worth pulling out of each file, if present.
CONSTANTS_OF_INTEREST = [
    "SEEDS", "EPSILON_LEVELS", "STRATIFIED_EPS", "DELTA", "MAX_GRAD_NORM",
    "CONFIGS", "TASK_CONFIGS",
]


def _literal_or_source(node: ast.AST) -> object:
    """ast.literal_eval when possible (plain literals), else the source text
    (e.g. `"cuda" if torch.cuda.is_available() else "cpu"`)."""
    try:
        return ast.literal_eval(node)
    except (ValueError, TypeError):
        return ast.unparse(node)


def extract_constants(tree: ast.Module) -> dict[str, object]:
    found: dict[str, object] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and len(node.targets) == 1 \
                and isinstance(node.targets[0], ast.Name) \
                and node.targets[0].id in CONSTANTS_OF_INTEREST:
            found[node.targets[0].id] = _literal_or_source(node.value)
    return found


def extract_cli_defaults(tree: ast.Module) -> dict[str, object]:
    """Every parser.add_argument(...) default= value in the file, keyed by flag."""
    defaults: dict[str, object] = {}
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                and node.func.attr == "add_argument"):
            continue
        flag = None
        if node.args and isinstance(node.args[0], ast.Constant):
            flag = node.args[0].value
        default = None
        has_default = False
        for kw in node.keywords:
            if kw.arg == "default":
                default = _literal_or_source(kw.value)
                has_default = True
        if flag is not None:
            # action="store_true" flags default to False even without an explicit default=
            is_store_true = any(
                kw.arg == "action" and isinstance(kw.value, ast.Constant)
                and kw.value.value == "store_true"
                for kw in node.keywords
            )
            if has_default:
                defaults[flag] = default
            elif is_store_true:
                defaults[flag] = False
    return defaults


def audit(path: Path) -> dict[str, object]:
    tree = ast.parse(path.read_text())
    merged: dict[str, object] = {}
    merged.update(extract_constants(tree))
    merged.update(extract_cli_defaults(tree))
    return merged


def render_report(a_name: str, a: dict, b_name: str, b: dict) -> str:
    keys = sorted(set(a) | set(b))
    lines = [
        "# Script divergence report — run_exp1.py vs privacy_utility_curves.py",
        "",
        "Generated by `revision_scripts/diff_exp1_vs_privacy_curves.py` (static AST audit, "
        "no training executed). Lists every setting that currently differs between the two "
        "scripts, so `run_prism_privacy_sweep.py` harmonises all of them, not just the ones "
        "already known about.",
        "",
        f"| Setting | `{a_name}` | `{b_name}` | Same? |",
        "|---|---|---|---|",
    ]
    for k in keys:
        va = a.get(k, "*(not set)*")
        vb = b.get(k, "*(not set)*")
        same = "yes" if repr(va) == repr(vb) else "**NO**"
        lines.append(f"| `{k}` | `{va}` | `{vb}` | {same} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    a = audit(SCRIPT_A)
    b = audit(SCRIPT_B)
    report = render_report(SCRIPT_A.name, a, SCRIPT_B.name, b)
    OUT.write_text(report)
    print(report)
    print(f"\nWritten to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
